name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     
      - name: Test with pytest
        run: |
          python3 -m pytest
      
      - name: Test webpages
        run: python3 tests/testPages.py
      
      - name: Test Forms
        run: python3 tests/testForms.py
        
      - name: Check code coverage                       
        run: |
          python3 -m coverage run -m unittest tests/testPages.py
          python3 -m coverage report
          python3 -m coverage html
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-Pages-report
           path: htmlcov
        
      - name: Check code coverage                       
        run: |
          python3 -m coverage run -m unittest tests/testForms.py
          python3 -m coverage report
          python3 -m coverage html
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-Forms-report
           path: htmlcov